src/Entity/Registra.php
<?php

namespace App\Entity;

use App\Repository\RegistraRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RegistraRepository::class)
 */
class Registra
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     *
     */

    private $hora;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha;

    /**
     * @ORM\ManyToOne(targetEntity=Servicio::class, inversedBy="registras")
     * @ORM\JoinColumn(nullable=false)
     */
    private $servicio_id;

    /**
     * @ORM\ManyToOne(targetEntity=usuario::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $usuario;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;



    public function getId(): ?int
    {
        return $this->id;
    }


    public function getHoraCita(): ?string
    {
        return $this->hora;
    }

    public function setHoraCita(string $hora): self
    {
        $this->hora = $hora;

        return $this;
    }

    public function getFechaCita(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFechaCita(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }




    public function getServicioId(): ?Servicio
    {
        return $this->servicio_id;
    }

    public function setServicioId(?Servicio $servicio_id): self
    {
        $this->servicio_id = $servicio_id;

        return $this;
    }

    public function getUsuario(): ?usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }


}

templates/back/back-api.html.twig
{% extends 'back.html.twig' %}

{% block title %}BackOffice | Index {% endblock %}

{% block body %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-6 text-center">
            <h1>Api Routes</h1>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-1" style="margin-top: -40px">
            <a href="{{ path('admin') }}">
                <button class="button-four bg-danger"><i class="fas fa-chevron-circle-left mx-1"></i>Atrás</button>
            </a></div>

        <div class="card col-lg-5 col-md-5 mt-5 mb-5 align-content-center">

            <h2 class="card-title p-3"><strong>Productos:</strong><a href="{{ path('api_productos_links') }}">&nbsp;/api/v1/productos</a></h2>
            <h2 class="card-title p-3"><strong>Producto/id:</strong><a href="{{ path('api_producto_show', {id: 3}) }}">&nbsp;/api/v1/productos/3</a>&nbsp;&nbsp;&nbsp;Ejemplo</h2>

        </div>
    </div>


</div>

{% endblock %}

templates/back/back-index.html.twig
{% extends 'back.html.twig' %}

{% block title %}BackOffice | Index {% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-7 col-md-10 col-lg-7 col-sm-11">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success mt-3" role="alert">
                        <i class="fas fa-check-circle mx-2"></i>
                        {{ message }}

                    </div>
                {% endfor %}

                {% for message in app.flashes('danger') %}
                    <div class="alert alert-error mt-3" role="alert">
                        <i class="fas fa-exclamation-circle mx-2"></i>
                        {{ message }}

                    </div>
                {% endfor %}
            </div>
        </div>


        <div class="container-fluid mt-5">
            <div class="row">
                <div class="col-2 mx-4">


                </div>
                <div class="card col-4 mt-3 mr-3" style="width: 18rem;">
                    <div class="card-header">
                        Últimos productos añadidos
                    </div>
                    <div class="list-group list-group-flush">

                        {% if productos %}
                        {% for producto in productos %}

                        <div class="list-group-item">
                            <img src="{{ asset(pictures_public_directory ~  producto.imagen)}}" height="50" width="50">
                            <span class="text-center mx-3">{{producto.nombre}}</span>
                            <span class="text-center mx-3" style="font-size: small">{{producto.categoria}}</span>
                            <span class="text-center mx-3">{{producto.precio}}€</span>
                            <span class="text-center mx-3" style="font-size: small">{{ producto.addedon | date("Y-m-s")}}</span>
                        </div>

                        {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
                <div class="card col-4 mt-3 mx-5" style="width: 18rem;">
                    <div class="card-header">
                        Últimos usuarios añadidos
                    </div>
                    <div class="list-group list-group-flush">

                        {% if usuarios %}
                            {% for usuario in usuarios %}

                                <div class="list-group-item">
                                    <img src="{{ asset(avatar_public_directory ~  usuario.avatar)}}" height="50" width="50">
                                    <span class="text-center mx-3">{{usuario.username}}</span>
                                    <span class="text-center mx-3">{{usuario.email}}</span>
                                    <span class="text-center mx-3">{{usuario.role}}</span>
                                </div>

                            {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid mt-5">
            <div class="row">
                <div class="col-2 mx-4">


                </div>
                <div class="card col-4 mt-3 mr-3" style="width: 18rem;">
                    <div class="card-header">
                        Últimos reservas registradas
                    </div>
                    <div class="list-group list-group-flush">

                        {% if reservas %}
                            {% for reserva in reservas %}

                                <div class="list-group-item">
                                    <span class="text-center mx-3">{{reserva.usuario.username}}</span>
                                    <span class="text-center mx-3">{{reserva.ServicioId.nombre}}</span>
                                    <span class="text-center mx-3">{{reserva.horaCita}}</span>
                                    <span class="text-center mx-3">{{  reserva.fechaCita | date("Y-m-d") }}</span>
                                </div>

                            {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
                <div class="card col-4 mt-3 mx-5" style="width: 18rem;">
                    <div class="card-header">
                        Últimos usuarios añadidos
                    </div>
                    <div class="list-group list-group-flush">

                        {% if usuarios %}
                            {% for usuario in usuarios %}

                                <div class="list-group-item">
                                    <img src="{{ asset(avatar_public_directory ~  usuario.avatar)}}" height="50" width="50">
                                    <span class="text-center mx-3">{{usuario.username}}</span>
                                    <span class="text-center mx-3">{{usuario.email}}</span>
                                    <span class="text-center mx-3">{{usuario.role}}</span>
                                </div>

                            {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/back/back-pedidos.html.twig
{% extends 'back.html.twig' %}

{% block title %}BackOffice | Index {% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row fila-inputs-productos">
            <div class="col-2"></div>
            <div class="col-7 col-lg-7 col-sm-10 mr-4 bg-light" style="border: 2px solid black">
                <form method="get" action="productos/filter"
                      class="form-inline">
                    <div class="form-group">
                        <input name="text"
                               value=""
                               type="text" placeholder="Buscar" aria-label="Search">
                    </div>
                    <div class="form-check-inline ml-3">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio" name="optradio" id="nombre" value="nombre">&nbsp;Nombre                        &nbsp;
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-input" type="radio" name="optradio" id="descripcion" value="descripcion">&nbsp;Descripcion                        &nbsp;
                        </label></div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-input" type="radio" name="optradio" id="both" value="both" checked>&nbsp;Ambos                        &nbsp;
                        </label>
                    </div>
                    <div class="form-group">
                        <button style="margin-top: 15px; margin-left: 0px" class="button-four" type="submit" name="botonFiltrar">Buscar</button>
                    </div>
                </form>
            </div>

        </div>

        <div class="container-fluid">
            <div class="container-fluid">
                <div class="row justify-content-start">
                    <div class="col-3"></div>
                    <div class="col-lg-8 col-8">
                        <table>
                            <tr>

                                <th class="text-center">Username</th>
                                <th class="text-center">Servicio</th>
                                <th class="text-center">Hora</th>
                                <th class="text-center">Fecha</th>
                                <th class="text-center">Acciones</th>
                            </tr>
                            {% if pedidos %}
                                {% for pedido in pedidos %}
                                    <tr>

                                        <td class="text-center">{{reserva.usuario.username}}</td>
                                        <td class="text-center">{{reserva.ServicioId.nombre}}</td>
                                        <td class="text-center">{{reserva.horaCita}}</td>
                                        <td class="text-center">{{  reserva.fechaCita | date("Y-m-d") }}</td>

                                        <td class="text-center" style="width: 140px"><a href="reservas/{{ pedido.id }}/edit">
                                                <button type="button" class="btn btn-warning my-1"><i class="fa fa-edit"></i> Editar</button>
                                            </a>
                                            <a href="reservas/{{ pedido.id }}/delete">
                                                <button type="button" class="btn btn-danger my-1"><i class="fa fa-trash"></i> Borrar</button>
                                            </a>
                                            <a href="reservas/{{ pedido.id }}/show">
                                                <button type="button" class="btn btn-info my-1 px-3 my-1"><i class="fa fa-eye"></i> Ver</button>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <h2>No hay reservas disponibles</h2>
                            {% endif %}
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/back/back-productos.html.twig
{% extends 'back.html.twig' %}

{% block title %}BackOffice | Index {% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row fila-inputs-productos">
            <div class="col-2"></div>
            <div class="col-7 col-lg-7 col-sm-10 mr-4 bg-light" style="border: 2px solid black">
                <form method="get" action="{{ path('back_productos_filter') }}"
                      class="form-inline">
                    <div class="form-group">
                        <input name="text"
                               value=""
                               type="text" placeholder="Buscar" aria-label="Search">
                    </div>
                    <div class="form-check-inline ml-3">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio" name="optradio" id="categoria" value="categoria">&nbsp;Categoria
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-input" type="radio" name="optradio" id="nombre" value="nombre">&nbsp;Nombre
                            &nbsp;
                        </label></div>
                    <div class="col-3 col-lg-3 col-sm-3 ml-5 bg-light">
                        <div class="form-group mt-2">
                            <label for="min" class="mr-1">Min</label>
                            <input name="min"
                                   value=""
                                   type="date" placeholder="Buscar" id="min" aria-label="Search">
                        </div>
                        <div class="form-group mt-2 mb-2">
                            <label for="max" class="mr-1">Max</label>
                            <input name="max"
                                   value=""
                                   type="date" placeholder="Buscar" id="max" aria-label="Search">
                        </div>
                    </div>
                    <div class="col-1 col-lg-1 col-sm-3 bg-light">
                        <h5>Busca entre 2 fechas</h5>
                    </div>
                    <div class="form-group mr-2">
                        <button style="margin-top: 15px; margin-left: 40px" class="button-four" type="submit"
                                name="botonFiltrar">Buscar
                        </button>
                    </div>
                </form>
            </div>

        </div>

        <div class="container-fluid">
            <div class="row justify-content-center">

                <div class="col-3 col-lg-6 ml-3">
                    <div>
                        <a style="text-decoration: none; color: white" class="btn" href="{{ path('create_product') }}"><button class="button-four bg-dark">
                                <i class="fa fa-plus-circle">
                                </i> Añadir producto</button></a>
                    </div>
                </div>
            </div>
                <div class="container-fluid">
                    <div class="row justify-content-start">
                        <div class="col-3"></div>
                        <div class="col-lg-8 col-8">
                    <table>
                        <tr>
                            <th class="text-center">Imagen</th>
                            <th class="text-center">Nombre</th>
                            <th class="text-center">Categoría</th>
                            <th class="text-center">Descripción</th>
                            <th class="text-center">Precio</th>
                            <th class="text-center">Añadido</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                        {% if pagination %}
                            {% for producto in pagination %}
                                <tr>
                                    <td class="text-center"><img src="{{ asset(pictures_public_directory ~  producto.imagen)}}" height="125" width="125"></td>
                                    <td class="text-center">{{producto.nombre}}</td>
                                    <td class="text-center">{{  producto.categoria }}</td>
                                    <td class="text-center">{{ producto.descripcion }}</td>
                                    <td class="text-center">{{ producto.precio}}</td>
                                    <td class="text-center">{{ producto.addedon | date("Y-m-s")}}</td>
                                    <td class="text-center" style="width: 140px"><a href="{{ path('productos_edit', {id: producto.id}) }}">
                                            <button type="button" class="btn btn-warning my-1"><i class="fa fa-edit"></i> Editar</button>
                                        </a>
                                        <a href="{{ path('productos_delete', {id: producto.id}) }}">
                                            <button type="button" class="btn btn-danger my-1"><i class="fa fa-trash"></i> Borrar</button>
                                        </a>
                                        <a href="{{ path('productos_showBack', {id: producto.id}) }}">
                                            <button type="button" class="btn btn-info my-1 px-3 my-1"><i class="fa fa-eye"></i> Ver</button>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <h2>No hay productos disponibles</h2>
                        {% endif %}
                    </table>

                            <div class="container-fluid">
                                <div class="row justify-content-center">
                                    <div class="col-1">
                                        <nav aria-label="Page navigation example">
                                            <div>
                                                {{knp_pagination_render(pagination)}}
                                            </div>
                                        </nav>

                                    </div>
                                </div>
                            </div>


                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/back/back-reservas.html.twig
{% extends 'back.html.twig' %}

{% block title %}BackOffice | Index {% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row fila-inputs-productos">
            <div class="col-2"></div>
            <div class="col-7 col-lg-7 col-sm-10 mr-4 bg-light" style="border: 2px solid black">
                <form method="get" action="{{ path('back_reservas_filter') }}"
                      class="form-inline">
                    <div class="form-group">
                        <input name="text"
                               value=""
                               type="text" placeholder="Buscar" aria-label="Search">
                    </div>
                    <div class="form-check-inline ml-3">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio" name="optradio" id="fecha" value="fecha">&nbsp;Fecha
                        </label>
                    </div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-input" type="radio" name="optradio" id="hora" value="hora">&nbsp;Hora                        &nbsp;
                        </label></div>
                    <div class="form-check-inline">
                        <label class="form-check-inline">
                            <input class="form-check-input" type="radio" name="optradio" id="both" value="both" checked>&nbsp;Ambos                        &nbsp;
                        </label>
                    </div>
                    <div class="form-group">
                        <button style="margin-top: 15px; margin-left: 0px" class="button-four" type="submit" name="botonFiltrar">Buscar</button>
                    </div>
                </form>
            </div>

        </div>

        <div class="container-fluid">
            <div class="row justify-content-center">

                <div class="col-3 col-lg-6 ml-3">
                    <div>
                        <a style="text-decoration: none; color: white" class="btn" href="{{ path('reservas_createBack') }}"><button class="button-four bg-dark">
                                <i class="fa fa-plus-circle">
                                </i> Añadir reserva</button></a>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row justify-content-start">
                    <div class="col-3"></div>
                    <div class="col-lg-8 col-8">
                        <table>
                            <tr>

                                <th class="text-center">Username</th>
                                <th class="text-center">Servicio</th>
                                <th class="text-center">Hora</th>
                                <th class="text-center">Fecha</th>
                                <th class="text-center">Acciones</th>
                            </tr>
                            {% if reservas %}
                                {% for reserva in reservas %}
                                    <tr>

                                        <td class="text-center">{{reserva.usuario.username}}</td>
                                        <td class="text-center">{{reserva.ServicioId.nombre}}</td>
                                        <td class="text-center">{{reserva.horaCita}}</td>
                                        <td class="text-center">{{  reserva.fechaCita | date("Y-m-d") }}</td>

                                        <td class="text-center" style="width: 140px"><a href="{{ path('reservas_edit', {id: reserva.id}) }}">
                                                <button type="button" class="btn btn-warning my-1"><i class="fa fa-edit"></i> Editar</button>
                                            </a>
                                            <a href="{{ path('reservas_delete', {id: reserva.id}) }}">
                                                <button type="button" class="btn btn-danger my-1"><i class="fa fa-trash"></i> Borrar</button>
                                            </a>
                                            <a href="{{ path('reservas_showBack', {id: reserva.id}) }}">
                                                <button type="button" class="btn btn-info my-1 px-3 my-1"><i class="fa fa-eye"></i> Ver</button>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <h2>No hay reservas disponibles</h2>
                            {% endif %}
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/back/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}BackOffice | Index {% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-7 col-md-10 col-lg-7 col-sm-11">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success mt-3" role="alert">
                        <i class="fas fa-check-circle mx-2"></i>
                        {{ message }}

                    </div>
                {% endfor %}

                {% for message in app.flashes('danger') %}
                    <div class="alert alert-error mt-3" role="alert">
                        <i class="fas fa-exclamation-circle mx-2"></i>
                        {{ message }}

                    </div>
                {% endfor %}
            </div>
        </div>


        <div class="container-fluid mt-5">
            <div class="row">
                <div class="col-2 mx-4">


                </div>
                <div class="card col-4 mt-3 mr-3" style="width: 18rem;">
                    <div class="card-header">
                        Últimos productos añadidos
                    </div>
                    <div class="list-group list-group-flush">

                        {% if productos %}
                        {% for producto in productos %}

                        <div class="list-group-item">
                            <img src="{{ asset(pictures_public_directory ~  producto.imagen)}}" height="50" width="50">
                            <span class="text-center mx-3">{{producto.nombre}}</span>
                            <span class="text-center mx-3">{{producto.categoria}}</span>
                            <span class="text-center mx-3">{{producto.precio}}</span>
                        </div>

                        {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
                <div class="card col-4 mt-3 mx-5" style="width: 18rem;">
                    <div class="card-header">
                        Últimos usuarios añadidos
                    </div>
                    <div class="list-group list-group-flush">

                        {% if usuarios %}
                            {% for usuario in usuarios %}

                                <div class="list-group-item">
                                    <img src="{{ asset(avatar_public_directory ~  usuario.avatar)}}" height="50" width="50">
                                    <span class="text-center mx-3">{{usuario.username}}</span>
                                    <span class="text-center mx-3">{{usuario.email}}</span>
                                    <span class="text-center mx-3">{{usuario.role}}</span>
                                </div>

                            {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid mt-5">
            <div class="row">
                <div class="col-2 mx-4">


                </div>
                <div class="card col-4 mt-3 mr-3" style="width: 18rem;">
                    <div class="card-header">
                        Últimos reservas registradas
                    </div>
                    <div class="list-group list-group-flush">

                        {% if reservas %}
                            {% for reserva in reservas %}

                                <div class="list-group-item">
                                    <span class="text-center mx-3">{{reserva.usuario.username}}</span>
                                    <span class="text-center mx-3">{{reserva.ServicioId.nombre}}</span>
                                    <span class="text-center mx-3">{{reserva.horaCita}}</span>
                                    <span class="text-center mx-3">{{  reserva.fechaCita | date("Y-m-d") }}</span>
                                </div>

                            {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
                <div class="card col-4 mt-3 mx-5" style="width: 18rem;">
                    <div class="card-header">
                        Últimos usuarios añadidos
                    </div>
                    <div class="list-group list-group-flush">

                        {% if usuarios %}
                            {% for usuario in usuarios %}

                                <div class="list-group-item">
                                    <img src="{{ asset(avatar_public_directory ~  usuario.avatar)}}" height="50" width="50">
                                    <span class="text-center mx-3">{{usuario.username}}</span>
                                    <span class="text-center mx-3">{{usuario.email}}</span>
                                    <span class="text-center mx-3">{{usuario.role}}</span>
                                </div>

                            {% endfor %}
                        {% else %}
                            <h2>No hay usuarios disponibles</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/back/productos-edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Juan Bisquert | Peluqueria{% endblock %}
{% block body %}
    <div class="container-fluid">

        <div class="container-fluid py-4">

            <div class="row justify-content-center mt-2 mr-5">
                <div class="col-1 mr-5">
                    <a href="../"><button class="button-four bg-danger"><i class="fas fa-chevron-circle-left mx-1"></i>Atrás</button></a></div>

                <div class="col-3 py-3 bg-light">
                    <h1 class="px-3 mb-5">Editar producto</h1>
                    <hr>
                    {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}